# yaml表示以上对象
person:
#  单引号会将 \n 作为字符串输出  双引号会将 \n 作为换行输出
#  双引号不会转义，单引号会转义
  boss: true
  birth: 2019/12/12
  age: 18
#  interests: [篮球,游泳]
  interests:
    - 篮球
    - 游泳
    - 18
#  animal: [阿猫,阿狗]
  animal:
    - jerry
    - mario
#  score:
#    english: 80
#    math: 90
  score: {english:128,math:136}
  salarys:
    - 3999
    - 4999.98
  pet:
    name: tomcat
    weight: 23.4
  allPets:
    sick:
      - {name: tom,weight: 47.99}
      - name: jerry
        weight: 47
      - name: 爱宠
        weight: 22
    health:
      - {name: cccc,weight: 47.99}
      - {name: aaaa,weight: 472.99}
  user-name: zhangsan
